---
- hosts: kafka
  remote_user: vagrant
  sudo: yes
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    download_folder: /opt
    java_name: "{{download_folder}}/jdk1.8.0_05"
    java_archive: "{{download_folder}}/jdk-8u5-linux-x64.tar.gz"
    scala_version: 2.9.3
    scala_archive: "/tmp/scala-{{scala_version}}.rpm"
    sbt_version: 0.13.5
    zookeeper_version: 3.4.6
    kafka_version: 0.8.1.1

  tasks:
    - name: Install Wget
      yum: name=wget state=present

    - include: tasks/install-java.yml
    - include: tasks/install-scala.yml
    - include: tasks/install-sbt.yml
    - include: tasks/install-zookeeper.yml  
    - include: tasks/install-kafka.yml

