- name: Check if scala is installed
  command: rpm -q scala
  register: scala_check
  ignore_errors: True

- name: Download Scala
  command: "wget -q -O {{scala_archive}} http://www.scala-lang.org/files/archive/scala-{{scala_version}}.rpm"
  when: scala_check.rc == 1

- name: Install scala
  command: "rpm -ivh {{scala_archive}}"
  when: scala_check.rc == 1

- name: Clean up
  file: state=absent path={{scala_archive}}
  when: scala_check.rc == 1