- name: Check if sbt is installed
  command: rpm -q sbt
  register: sbt_check
  ignore_errors: True

- name: Download sbt
  get_url: url=https://bintray.com/sbt/rpm/rpm dest=/etc/yum.repos.d/bintray-sbt-rpm.repo
  when: sbt_check.rc == 1

- name: Install sbt
  yum: name=sbt state=present
  when: sbt_check.rc == 1
