
- name: Download Kafka {{ kafka_version }}
  get_url: url=http://www.mirrorservice.org/sites/ftp.apache.org/kafka/{{ kafka_version }}/kafka-{{ kafka_version }}-src.tgz dest=/tmp/kafka-{{ kafka_version }}-src.tar.gz mode=0644 force=no timeout=180

- name: Create Group
  group: name=kafka state=present

- name: Create User
  user: name=kafka comment="Kafka" group=kafka

- name: Unpack the tar
  shell: tar -xzvf /tmp/kafka-{{ kafka_version }}-src.tar.gz chdir=/tmp/ creates=/tmp/kafka-{{ kafka_version }}-src

- name: run SBT update
  shell: sbt update chdir=/tmp/kafka-{{ kafka_version }}-src creates=/usr/local/kafka-{{ kafka_version }}

- name: run SBT package
  shell: sbt package chdir=/tmp/kafka-{{ kafka_version }}-src creates=/usr/local/kafka-{{ kafka_version }}

- name: Copy Kafka into place
  shell: mv /tmp/kafka-{{ kafka_version }}-src /usr/local/kafka-{{ kafka_version }} creates=/usr/local/kafka-{{ kafka_version }}

- name: Symlink /usr/local/kafka to this version
  file: src=/usr/local/kafka-{{ kafka_version }} dest=/usr/local/kafka state=link owner=kafka group=kafka

- name: Switch Scala version numbers
  replace: dest=/usr/local/kafka/gradle.properties regexp='^scalaVersion=.*$' replace='scalaVersion={{ scala_version }}'
  
- name: Run Gradle to build Kafka
  shell: ./gradlew jar chdir=/usr/local/kafka creates=/usr/local/kafka/core/build/
  
- name: Install the Kafka service handler
  copy: src=init.d/kafka dest=/etc/init.d/ mode=0755
  
- name: Switch Scala version numbers in service handler
  replace: dest=/etc/init.d/kafka regexp='^export SCALA_VERSION=.*$' replace='export SCALA_VERSION={{ scala_version }}'

- name: Change directory owner
  file: path=/usr/local/kafka-{{ kafka_version }} state=directory owner=kafka group=kafka recurse=yes

- name: Run the kafka service
  service: name=kafka state=started enabled=yes
  